name: "Use composite action from the other repository"

on:
  push:
  workflow_dispatch:
    inputs:
      versionB:
        description: 'main'
        required: true
        default: '2.0.0'
        type: string

jobs:
  greetings_with_composite_action:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - run: echo "=== START ==="
      - uses: actions/checkout@v3
        with:
          repository: 'kyanny-corp-enterprise-cloud-testing/zd-1669617-composite-action-called'
          ref: ${{inputs.versionB}}
          path: 'zd-1669617-composite-action-called'
      - run: ls -lah .
      - run: ls -lah zd-1669617-composite-action-called
      - uses: ./zd-1669617-composite-action-called
        with:
          versionB: '2.0.0'
      - run: echo "======"
      - uses: kyanny-corp-enterprise-cloud-testing/zd-1669617-composite-action-called@main
        with:
          versionB: '3.0.0'
      - run: echo "=== END ==="
