name: "Use composite action from the other repository"

on:
  push:
  workflow_dispatch:

jobs:
  greetings_with_composite_action:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - run: echo "=== START ==="
      - uses: zd-1669617-composite-action-called@main
      - run: echo "=== END ==="
