name: "Use composite action from the other repository"

on:
  push:
  workflow_dispatch:

jobs:
  greetings_with_composite_action:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - run: echo "=== START ==="
      - uses: actions/checkout@v3
        with:
          repository: 'kyanny-corp-enterprise-cloud-testing/zd-1669617-composite-action-called'
          ref: 'main'
          path: 'zd-1669617-composite-action-called'
      - run: ls -lah .
      - run: ls -lah zd-1669617-composite-action-called
      - uses: ./zd-1669617-composite-action-called
      - run: echo "======"
      - uses: kyanny-corp-enterprise-cloud-testing/zd-1669617-composite-action-called@main
      - run: echo "=== END ==="
